### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1442] opened 2020-10-02 08:15 UTC
Reproduction steps

```
#clean repo
git clean -dfx
#install dependencies
npm install
```
```
Observe:

Loading "svg-sprites.js" tasks...ERROR
>> TypeError: Object.values is not a function
Warning: Task "svg-sprites" not found. Use --force to continue.

```

**Comment by korneliakobiela** [comment] 2020-10-02 14:39
I've not found why the issue is in particular. This is a problem with some dependencies of dependencies (dependency hell :imp: ). I suppose that is a bad version of CSS-WHAT and that caused failing.

**Comment by HunseopJeong** [comment] 2020-10-05 05:46
I got a same error. How about upversioning the node?
We used the v6.16. I think It is too old version.

**Comment by lslachciak** [comment] 2020-10-05 06:05
We already did some tries regarding node upverisoning but this is quite big change, not sure if this is right for 1.2 release.
Also this would make sense if this would solve this issue.

**Comment by egorshulga** [comment] 2020-10-05 15:04
I suppose that's because `Object.values()` is available only starting with Node v7 ([see](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values#Browser_compatibility)). v6.16.0 is way too old.

Anyway, I was lucky enough to build the library with Node v7

**Comment by korneliakobiela** [comment] 2020-10-05 15:42
Yeah, I see it. I am working on make it works well again. Now I see for version Node 8.17 works well, but our tests started to fail.

**Comment by lslachciak** [comment] 2020-10-06 10:43
I think this issue was solved with https://github.com/Samsung/TAU/pull/1444 so we can close it.
For bumping node I opened new issue: https://github.com/Samsung/TAU/issues/1445

**Closed as completed** 2020-10-06 10:43 UTC
Labels: important
