### ISSUE TITLE
defering TAU load causes problems

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#190] opened 2019-07-08 14:56 UTC
Please check attached example
[SinglePage.zip](https://github.com/Samsung/TAU/files/3368953/SinglePage.zip)

If you defer page TAU load in app, next instance of TAU app loaded in the same iframe is not able to load TAU.

In order to get correct behavior in TAU replace

<iframe id="TAUFRAME" src="BAD.html" width="800" height="1000"></iframe>
with 
<iframe id="TAUFRAME" src="OK.html" width="800" height="1000"></iframe>

BAD and OK html just differ with defer keyword in a header

**Comment by TomaszLukawskiSam** [comment] 2019-07-09 11:36
I'm during verification of this problem, but at the moment, in my opinion cause the issue is Router (tau.router.Router.getInstamce() ). After overwrite document content the Router still contains old instance of page container. This blocks build process.

**Comment by TomaszLukawskiSam** [comment] 2019-07-12 14:22
PR has already merged.

**Closed** 2019-07-31 09:32 UTC
Labels: 1.0
