### ISSUE TITLE
Rotary of bezel changes position of list twice on one tick

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#289] opened 2019-08-05 04:41 UTC
Issue is occurring on Emulator 5.0.

```
Model=Tizen5/Unified;
Build=tizen-unified_20181024.1;
Release=20181024.1;
[Build]
Type=eng;
Date=20181024_040528;
Time=04:05:28;
Variant=NONE;
ID=tizen-unified;
```

**Comment by pkaczmarczy** [comment] 2019-08-06 11:48
The root cause is related to emulator itself.
I have created an empty web app in Tizen Studio (without TAU) and I have registered listener on "rotarydetent" event.
On emulator "rotarydetent" event was triggered twice for each bezel movement.
Here are some logs:
`D/POWER_MANAGER( 2212): input.c: process_event(93) > type 2 fd 14
I/POWER_MANAGER( 2212): core.c: reset_timeout(703) > Reset Timeout (293000)ms
D/XWALK   ( 3635): web_application.cc: OnRotaryEvent(1141) > OnRotaryEvent
D/XWALK   ( 3635): web_application.cc: OnRotaryEvent(1141) > OnRotaryEvent
D/POWER_MANAGER( 2212): input.c: process_event(93) > type 2 fd 14
D/ConsoleMessage( 3635): [3jkfl3UCJP] file:///js/main.js:22: Rotarydetent event triggered
D/ConsoleMessage( 3635): [3jkfl3UCJP] file:///js/main.js:22: Rotarydetent event triggered
`
On physical device with an event was triggered only once.
Logs:
`D/POWER_MANAGER(  286): input.c: process_event(93) > type 2 fd 18
I/POWER_MANAGER(  286): core.c: reset_timeout(703) > Reset Timeout (3600000)ms
D/POWER_MANAGER(  286): input.c: process_event(93) > type 2 fd 18
D/XWALK   ( 1335): web_application.cc: OnRotaryEvent(1134) > OnRotaryEvent
D/POWER_MANAGER(  286): input.c: process_event(93) > type 2 fd 18
D/POWER_MANAGER(  286): input.c: process_event(93) > type 2 fd 18
D/ConsoleMessage( 1335): [3jkfl3UCJP] file:///js/main.js:22: Rotarydetent event triggered
`

**Comment by TomaszLukawskiSam** [comment] 2019-08-06 11:51
@lslachciak 
Based on above comment we can close this issue as not related to TAU project and reporting issue to TizenStudio team.

**Comment by lslachciak** [comment] 2019-08-08 12:50
After creating issue to TizenStudio team we can close it

**Comment by lslachciak** [comment] 2019-08-12 12:18
@pkaczmarczy could you recheck issue on latest emulator?

**Comment by pkaczmarczy** [comment] 2019-08-12 12:24
With Build=tizen-unified_20181024.1; issue exists.

With newer emulator images issue does not occur, tested with:
 - tizen-unified_20190812.1
 - tizen-4.0-unified_20190802.1

**Comment by lslachciak** [comment] 2019-08-12 12:25
because it is not reproducible on latest emulator, closing issue

**Closed by lslachciak** 2019-08-12 12:25 UTC
Labels: 1.1, emulator, wearable
