### ISSUE TITLE
Marquee widget reset

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#475] opened 2019-11-14 07:34 UTC
ui-marquee widget should
- stop when another widget is selected and reset its state
- when animation stops widget should be reset

**Comment by pkaczmarczy** [comment] 2019-11-14 15:26
This issue is under investigation. The mechanics responsible for animations is quite complex, it takes time to find the root cause of the problem.

**Comment by pkaczmarczy** [comment] 2019-11-18 09:19
PR has been already merged.

**Closed as completed** 2019-11-22 11:55 UTC
Labels: 1.0, in review, important
