### ISSUE TITLE
Arclistview and "more options" does not work

### ISSUE THREAD

**Issue by Vascomax** [Samsung/TAU#1151] opened 2020-06-01 16:54 UTC
While adding the "more options" button to a page with an Arclistview, the three dots are shown, but a click on it is not recognized.
I use the default tizen studio 3.7 and it happened in a wearable (tizen 4.0) project.
Is anyone else having this problem too?

**Comment by HunseopJeong** [comment] 2020-06-08 23:55
@Vascomax,
You need to initialize the selector when opening the page.
You can refer to the UIComponents - contents - moreoptions -moreoptions.js
```
	page.addEventListener("pagebeforeshow", function () {
		var radius = window.innerHeight / 2 * 0.8;

		clickHandlerBound = clickHandler.bind(null);
		handler.addEventListener("click", clickHandlerBound);
		if (tau.support.shape.circle) {
			selector = tau.widget.Selector(elSelector, {itemRadius: radius});
		}
	});
```

**Comment by Vascomax** [comment] 2020-06-10 00:31
@HunseopJeong,
thanks for your reply. I did combine the UIComponents example for more-options with the TAUlist, so I had that section and moreoptions.js included. I did some tests with changing the list style via circle-helper. 
If I change there ArcListview to SnapListview, without changing anything else in the code, the more options works, as long as the list is not scrolled. The selector opens correctly. But as soon as the list is scrolled, the button disappears and does not come back. (so there seems to be an issue with SnapListview as well...). But I want to use ArcList, so I was focussing on that.
At least with the ArcListview the button is showed all the time, but is not clickable at all.

I added some screenshots:

ArcListviewSituation (button always shown but not working)
![arclistview_more_options](https://user-images.githubusercontent.com/65168100/84213422-e6274f00-aac0-11ea-825b-d1e25a61e82b.png) 
SnapListview before scrolling (button shown and working)
![snaplist_more_before_Scroll](https://user-images.githubusercontent.com/65168100/84213510-238bdc80-aac1-11ea-990c-7ff90d39128e.png)
SnapListview after scrolling (button not shown)
![snaplist_more_after_scroll](https://user-images.githubusercontent.com/65168100/84213770-d3f9e080-aac1-11ea-82ac-41421da198ac.png)

**Comment by HunseopJeong** [comment] 2020-06-16 11:56
@Vascomax, 
You can fix the issue with z-index.
```
		<div class="ui-content ui-content-padding">
                         // Set the z-index property to the more options button.
			<button class="ui-more" type="button" style="z-index:100;">
				More Options
			</button>
			<ul class="ui-listview">
				<li>
					<a href="#">
						List 1
					</a>
				</li>
				<li>
					<a href="#">
						List 2
					</a>
				</li>
				<li>
					<a href="#">
						List 3
					</a>
				</li>
				<li>
					<a href="#">
						List 4
					</a>
				</li>
				<li>
					<a href="#">
						List 5
					</a>
				</li>
				<li>
					<a href="#">
						List 6
					</a>
				</li>
			</ul>
		</div>
```
It seems to be a problem caused by the more option button being obscured by the list element.

**Comment by Vascomax** [comment] 2020-06-16 14:40
@HunseopJeong,
Thanks for that quick fix. Works well for me. Keep up the good work, I very much appreciate it.

**Comment by HunseopJeong** [comment] 2020-07-03 07:00
PR was merged.

**Closed as completed by HunseopJeong** 2020-07-03 07:00 UTC
Labels: bug, wearable
