### ISSUE TITLE
Floating actions example  - not working

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#156] opened 2019-06-14 06:55 UTC
Reproduction steps:
1. Visit:
https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/controls/floatingactions/on-page.html
2. Not possibleto make any action

**Comment by TomaszLukawskiSam** [comment] 2019-07-17 11:46
Floating Button doesn't support mouse events - supports only touch events.

**Comment by TomaszLukawskiSam** [comment] 2019-07-18 07:31
After verification I have to change conclusions. Floating Button supports mouse events.The issue is more complicated and I have proofs that it can be issue in web browser engine.

**Comment by lslachciak** [comment] 2019-08-01 10:02
@TomaszLukawskiSam  PR was merged, can we put this issue into review?

**Comment by TomaszLukawskiSam** [comment] 2019-08-01 13:27
I think that we can close the issue.

**Closed** 2019-08-02 09:27 UTC
Labels: 1.0, 1.1, in review
