### ISSUE TITLE
Title text margin not applied

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1027] opened 2020-04-27 11:19 UTC
Title text margin not applied
GUI feedback p. 6

**Comment by TomaszLukawskiSam** [comment] 2020-05-05 10:53
@lslachciak 
Do you have some screenshot? Is this issue of AppBar title?

**Comment by lslachciak** [comment] 2020-05-06 07:42
@TomaszLukawskiSam please check page 6 in [Webapp]SR_GUI_Feedback_200413.pptx

**Comment by TomaszLukawskiSam** [comment] 2020-05-06 09:13
> @TomaszLukawskiSam please check page 6 in [Webapp]SR_GUI_Feedback_200413.pptx

The issue is resolved by PR #1061

**Comment by TomaszLukawskiSam** [comment] 2020-05-06 17:35
Patch has been merged.

**Comment by lslachciak** [comment] 2020-05-07 08:09
ok

**Closed as completed by lslachciak** 2020-05-07 08:09 UTC
Labels: 1.2, in review, mobile, UXF
