### ISSUE TITLE
Add unit tests for Graph widget

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU#177] opened 2019-07-02 13:31 UTC
There are no unit tests for Graph widget.

**Comment by lslachciak** [comment] 2019-07-17 07:40
@pkaczmarczy please share current status of this issue here - in progress/susended/PR ready etc..

**Comment by pkaczmarczy** [comment] 2019-07-17 09:17
Currently work on this issue is suspended because of higher priority tasks.

**Comment by TomaszLukawskiSam** [comment] 2019-08-14 08:05
The issue is complicated because command line test engine (based on PhantomJs) is not supporting bundle file.

**Comment by TomaszLukawskiSam** [comment] 2019-09-02 11:45
The PR has already merged.

**Closed** 2019-09-02 12:55 UTC
Labels: 1.1, in review
