### ISSUE TITLE
Option menu icons disappearing on Gear S3.

### ISSUE THREAD

**Issue by martijnvankekem** [Samsung/TAU#369] opened 2019-09-06 09:48 UTC
When using the 'More options circle' widget on a wearable device, the icons disappear upon selecting, only on the Gear S3 (as far as I found out).

The reason behind this is that the transform: scale(1) property when selected is replaced by transform: scale(0, 8236), while it should be replaced with scale(0.8236) in order to apply the correct scale.

I was able to 'hack' a fix by adding a .replace("scale(0, 8236)", "scale(0.8236)") in the code, but wasn't able to find out the reason of this happening on the Gear S3.

It's not in all versions, but at least in 1.0.3 and I think it was also in the latest 1.1 release.

**Comment by lslachciak** [comment] 2019-09-09 08:04
We have this on to do list.

**Comment by lslachciak** [comment] 2019-09-09 08:29
@martijnvankekem could you attach sample app so we can try reproduce this issue?

**Comment by martijnvankekem** [comment] 2019-09-12 18:48
I was able to fix this issue with the following 'hack', which of course isn't something you'd want in a production version:

1. I changed the ITEM_NORMAL_SCALE to 0.8 for simplicity
2. I added these lines below the `[obj].style.transform.replace(DEFAULT.ITEM_ACTIVE_SCALE,
							DEFAULT.ITEM_NORMAL_SCALE);` in the ns.widget.wearable.Selector._setActiveItem function and also below the `newTransformStyle = transform.replace(DEFAULT.ITEM_NORMAL_SCALE,
						DEFAULT.ITEM_ACTIVE_SCALE);` line.

`active.style.transform = active.style.transform.replace("scale(0, 8)", "scale(0.8)");`
`active.style.transform = active.style.transform.replace("scale(0,8)", "scale(0.8)");`

**Comment by TomaszLukawskiSam** [comment] 2019-09-15 07:49
I cannot reproduce the issue. I try to understand what happen. In my opinion possible are two options:
1.The issue is caused by device localization and  a changing number format from "0.8" to "0,8" in web engine.
2. CSS "scale()" property allows one or two arguments. Maybe web engine converted this style argument from one argument to two arguments eg. "scale(0.8)" to "scale(0, 8)"

**Comment by TomaszLukawskiSam** [comment] 2019-09-15 08:22
@martijnvankekem 
I prepared patch (https://github.com/Samsung/TAU/pull/389) for a test.

**Comment by ampanasiuk** [comment] 2019-09-26 07:24
Reproducible on Galaxy Watch. Thanks to @martijnvankekem for debugging the root cause. I've tweaked the solution a bit in #408.

**Comment by TomaszLukawskiSam** [comment] 2019-09-30 07:25
The PR has been merged. Can we close the issue?

**Closed** 2019-09-30 07:38 UTC
Labels: important, in progress
